### ISSUE TITLE
xr.to_netcdf export changes 'dtype' after summer days calculation

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#89]
Creating test data sets for the CCSC portal when I came across this. Can someone confirm they get the same error?

description:

- Calculate summer days (su) (Note using the daily downsampler for now as test datasets have different calendars)
- Manual add attributes before export 
- data type of 'su' before export is float64 : figure / map of values ok
- export using to_netcdf
- 'su' data type of newly exported file is 'timedelta64[ns]'
- values are large integers (e.g. days since or similar)

Code to reproduce using nrcan daily test data
```python
from xclim.utils import daily_downsampler as dds
import xarray as xr
from glob import os
import numpy as np

xr.set_options(enable_cftimeindex=True)

infile = '/home/travis/PAVICSdev/XCLIMdev/github/tests/testdata/NRCANdaily/nrcan_canada_daily_tasmax_1990.nc'

freqs = ['MS']  # , 'QS-DEC', 'YS']
ds = xr.open_dataset(infile)
su = (ds.tasmax > 25.0+273.15) * 1.0
for f in freqs:

    grouper = dds(su, f)
    output = grouper.sum(dim='time')
    time1 = dds(ds.time, freq=f).first()

    ds.coords['counter'] = ds.time
    ds.counter.values = np.ones(ds.time.shape)

    output.coords['time'] = ('tags', time1.values)
    output = output.swap_dims({'tags': 'time'})
    output = output.sortby('time')
    output.attrs = ds.tasmax.attrs
    output.attrs['units'] = 'days'
    output.attrs['standard_name'] = 'summer_days'
    output.attrs['long_name'] = 'summer days'
    output.attrs['description'] = 'Number of days where daily maximum temperature exceeds 25℃'
    output = output.drop(['tags'])

    # use original file as template
    ds1 = xr.open_dataset(infile, drop_variables=['tasmax', 'time','time_vectors','ts'])
    ds1.coords['time'] = output.time.values
    ds1['su'] = output

    comp = dict(zlib=True, complevel=5)
    encoding = {var: comp for var in ds1.data_vars}
    print(os.path.basename(infile).replace('.nc', '_SummerDays-' + f) + ' : writing ' + f + ' to netcdf')
    # with dask.config.set(pool=ThreadPool(4)):

    ds1.to_netcdf('~/testNRCANsummerdays.nc', format='NETCDF4', encoding=encoding)

    ds2 = xr.open_dataset('~/testNRCANsummerdays.nc')
    print(ds1)
    print(ds2)
    print(ds1.su.max())
    print(ds2.su.max())
```

**Comment by tlogan2000** [comment]
This seems to be a problem with xarray assuming that my newly created variable's units ('days') should be automatically converted to a date object when I reread from the .nc file 

The original data file is in fact fine even when units are 'days' (reading in matlab or netCDF4) show that data values are ok...  but it is xarray doing an automatic reading of the units that seems to be that trouble

**Comment by tlogan2000** [comment]
This a known issue : https://github.com/pydata/xarray/issues/1621
with work in progress : https://github.com/pydata/xarray/pull/2105

Will leave the issue open for now

**Comment by Zeitsperre** [comment]
Moving this to xclim v1.2 milestone and marking as wontfix as this is an upstream issue. This bug will need to be documented as a known issue if/when we release a stable version.

**Comment by huard** [comment]
@tlogan2000 It looks like this has been fixed upstream, can you confirm ?

**Comment by Zeitsperre** [comment]
@huard 

I just ran @tlogan2000 's script using my own daily tasmax example data. I also freshly installed all my conda libraries and installed xarray from their git master branch. There still seems to be a problem:
```
Coordinates:
  * lat       (lat) float64 -87.86 -85.1 -82.31 -79.53 ... 82.31 85.1 87.86
  * lon       (lon) float64 0.0 2.812 5.625 8.438 ... 348.8 351.6 354.4 357.2
  * time      (time) object 2006-01-01 12:00:00 ... 2100-12-01 12:00:00
    height    float64 2.0
Dimensions without coordinates: bnds
Data variables:
    lat_bnds  (lat, bnds) float64 ...
    lon_bnds  (lon, bnds) float64 ...
    su        (time, lat, lon) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0

...

Coordinates:
  * lat       (lat) float64 -87.86 -85.1 -82.31 -79.53 ... 82.31 85.1 87.86
  * lon       (lon) float64 0.0 2.812 5.625 8.438 ... 348.8 351.6 354.4 357.2
  * time      (time) object 2006-01-01 12:00:00 ... 2100-12-01 12:00:00
    height    float64 ...
Dimensions without coordinates: bnds
Data variables:
    lat_bnds  (lat, bnds) float64 ...
    lon_bnds  (lon, bnds) float64 ...
    su        (time, lat, lon) timedelta64[ns] ...
```

**Comment by tlogan2000** [comment]
I almost universally use the following for avoiding any troubles related to this :
```
ds = xr.open_dataset(infile, decode_times=False)
ds['time'] = xr.decode_cf(ds).time
```

**Comment by huard** [comment]
Ok, thanks for the update.

**Comment by aulemahal** [comment]
This is still a problem in xarray's, maybe we could add a warning in the `declare_units` decorator to warn the user of this behaviour?
@tlogan2000

**Comment by Zeitsperre** [comment]
I'm thinking it might be good to have a note about this somewhere in the documentation, be it in our static pages or in the example notebook as a potential user trip-fall.

The really over-the-top solution would be to add a decorator that appends a warning to the docstring of indices that do this but, as @aulemahal and I discussed offline earlier, this is something that all xarray users need to be careful about in general. Well beyond the scope of xclim.

**Comment by tlogan2000** [comment]
I think the simple solution would be fine for now.  Just to clarify the data is written to disk fine.  It is in the re=reading of the file that xarray tries to be helpful and converts data_vars with units of 'days' to timedelta64s (I think)..

**Comment by tlogan2000** [comment]
Note xarray 0.16 has added a `decode_timedelta` flag to the `open_dataset` and `open_mfdataset` methods that resolves this issue.  I would suggest we that we begin using adding it for any demo code that we produce
